Translate vulkan_workflow Title ~ Vulkan SDK section
hyoyoung/22-tutorials-ex pull request #22
Opened 2022-07-21 18:15 UTC by YunjinJo

관련 이슈 번호
============
- 이슈 번호: #1 

PR 종류
============
- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

PR 설명
============
prototype_source 폴더의 [vulkan_workflow](https://github.com/hyoyoung/22-tutorials-ex/blob/master/prototype_source/vulkan_workflow.rst) 파일을 번역하였습니다.
제목 ~ Vulkan SDK 섹션까지 번역 하였습니다.

2022-07-22 09:41 UTC, gorae17 approved these changes
이슈 없습니다👍

2022-07-22 10:39 UTC, updaun commented on prototype_source/vulkan_workflow.rst
> +파이토치 1.7은 Vulkan 그래픽과 컴퓨팅 API를 지원하는 GPU에서 모델 추론(inference)을 실행하는 것을 지원합니다. 주 목표 디바이스는 안드로이드 장치의 모바일 GPU입니다. Vulkan 백엔드는 Vulkan을 지원하는 Intel 통합 GPU와 같은 장치를 사용해 Linux, Mac 그리고 Windows 데스크톱 빌드에서도 사용할 수 있
파이토치를 PyTorch로 사용해야 할까요?
다른 부분들은 다 PyTorch로 번역하신 것 같아요!

2022-07-22 10:46 UTC, updaun approved these changes
와우.. 작업이 빠르시네요! 대단하십니다! 😀

2022-07-22 17:05 UTC, bub3690 commented
저도 이슈 없습니다!

2022-07-24 08:57 UTC, hyoyoung requested changes
전반적으로 잘되어있습니다
소소한 수정이 필요합니다

2022-07-24 08:57 UTC, hyoyoung commented on prototype_source/vulkan_workflow.rst
> +============================================
위의 소제목이 크기에 맞다면 굳이 =를 늘릴 필요는 없을듯합니다

2022-07-24 08:57 UTC, hyoyoung commented on prototype_source/vulkan_workflow.rst
> +PyTorch 1.7은 Vulkan 그래픽과 컴퓨팅 API를 지원하는 GPU에서 모델 추론(inference)을 실행하는 것을 지원합니다. 주 목표 디바이스는 안드로이드 장치의 모바일 GPU입니다. Vulkan 백엔드는 Vulkan을 지원하는 Intel 통합 GPU와 같은 장치를 사용해 Linux, Mac 그리고 Windows 데스크톱 빌드에서도 사용할
실행하는 것을 지원합니다 보다는
실행을 지원합니다로 의역하면 어떨까요

2022-07-24 08:57 UTC, hyoyoung commented on prototype_source/vulkan_workflow.rst
> +PyTorch 1.7은 Vulkan 그래픽과 컴퓨팅 API를 지원하는 GPU에서 모델 추론(inference)을 실행하는 것을 지원합니다. 주 목표 디바이스는 안드로이드 장치의 모바일 GPU입니다. Vulkan 백엔드는 Vulkan을 지원하는 Intel 통합 GPU와 같은 장치를 사용해 Linux, Mac 그리고 Windows 데스크톱 빌드에서도 사용할
주 목표 디바이스보다는 주 목표 기기로 변경하면 어떨까요?

2022-07-24 08:57 UTC, hyoyoung commented on prototype_source/vulkan_workflow.rst
> +PyTorch 1.7은 Vulkan 그래픽과 컴퓨팅 API를 지원하는 GPU에서 모델 추론(inference)을 실행하는 것을 지원합니다. 주 목표 디바이스는 안드로이드 장치의 모바일 GPU입니다. Vulkan 백엔드는 Vulkan을 지원하는 Intel 통합 GPU와 같은 장치를 사용해 Linux, Mac 그리고 Windows 데스크톱 빌드에서도 사용할
프로토타입은 그대로 써도 좋지만 원형 수준이나, 초기 수준으로 의역하면 알아듣기 편할 것 같습니다

2022-07-24 14:19 UTC, hyoyoung approved these changes
good

2022-09-14 09:06 UTC, merged