B조: Korean translation practice for flask_rest_api_tutorial.py - 유연승
hyoyoung/22-tutorials-ex pull request #24
Opened 2022-07-22 10:22 UTC by yuyeonseung

flask_rest_api_tutorial.py 번역입니다

2022-07-22 10:54 UTC, garam24 commented on intermediate_source/flask_rest_api_tutorial.py
> +이미지를 디텍션하는 사전학습된 DenseNet 121 모델을 배포해봅시다.
어느 정도 수준으로 한국어로 해석이 되어야할지 저도 잘 감이 없는데요

이미지를 디텍션하는 -> 이미지를 감지하는? 검출하는? 등으로 수정되면 어떨지 의견드립니다.

2022-07-22 10:54 UTC, garam24 commented on intermediate_source/flask_rest_api_tutorial.py
> +이러한 배포방법으로 플라스크를 사용하는 것이 PyTorch 모델의 서비스를 시작하는 가장 쉬운 방법이지만 고성능 요구 사항이 있는 사용 사례에서는 작동하지 않습니다.
아래와 같이 수정하면 조금 더 자연스러울 것 같아 제안드립니다.

플라스크를 사용하여 이러한 방식으로 배포하는 것이 PyTorch 모델의 서비스를 시작하는 가장 쉬운 방법이지만,
고성능 요구 사항이 있는 경우에는 적합하지 않습니다.

2022-07-22 10:54 UTC, garam24 commented on intermediate_source/flask_rest_api_tutorial.py
> +# 의존성
뜻 자체는 '의존성'이 맞지만 '필요한 라이브러리들' 이런 식으로 번역이 되면 어떨까요?
(이런 부분에 대해서 번역 기준이 있는지 잘 모르겠네요; ㅎㅎ)

2022-07-24 07:26 UTC, dhlee-work commented on intermediate_source/flask_rest_api_tutorial.py
> +이미지를 디텍션하는 사전학습된 DenseNet 121 모델을 배포해봅시다.
detects the image가 맞는 표현일까요?.. 이미지에서 ~를 검출하다가 맞는 표현일것 같은데요.// 디텍션은 검출 등으로 수정되면 어떨지요?

2022-07-24 09:03 UTC, hyoyoung requested changes
전반적으로 잘되어있습니다
몇가지 수정 부탁드립니다

2022-07-24 09:03 UTC, hyoyoung commented on intermediate_source/flask_rest_api_tutorial.py
> +**번역**: 유연승
author는 저자로
번역항목에서는 본인 github이나 이메일로 부탁드립니다

2022-07-24 09:03 UTC, hyoyoung commented on intermediate_source/flask_rest_api_tutorial.py
> +이는 PyTorch 모델을 상용화로 배포하는 튜토리얼 중 첫 번째입니다.
'이는'은 빠져도 좋을 것 같습니다

2022-07-24 09:03 UTC, hyoyoung commented on intermediate_source/flask_rest_api_tutorial.py
> +# 우리의 API 앤드포인트는 이미지를 포함하는 "file" 매개 변수를 HTTP POST로 "/predict"에 요청할 것입니다.
강조의 의미가 아니면 주어는 생략합니다

2022-07-25 12:33 UTC, hyoyoung commented
수정한 부분이 없어보이는데 혹시 reviewer만 추가해주셨나요?

2022-07-25 12:35 UTC, yuyeonseung commented
넵 맞습니다 수정하고 눌렀어야하는데 잘못눌렀습니다...!

2022년 7월 25일 (월) 오후 9:33, Hyoyoung CHANG ***@***.***>님이 작성:

> 수정한 부분이 없어보이는데 혹시 reviewer만 추가해주셨나요?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hyoyoung/22-tutorials-ex/pull/24#issuecomment-1193991358>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALYZHOKXXTYVSZLHPV3IDSLVV2CS5ANCNFSM54K4MLDQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-02 15:17 UTC, closed without merging