C조  prototype_source/tracing_based_selective_build.rst 번역
hyoyoung/22-tutorials-ex pull request #26
Opened 2022-07-22 14:59 UTC by bub3690

관련 이슈 번호
============
- 이슈 번호: #16   

PR 종류
============

- [ ] 오탈자를 수정하거나 번역을 개선하는 기여
- [x] 번역되지 않은 튜토리얼을 번역하는 기여
- [ ] 공식 튜토리얼 내용을 반영하는 기여
- [ ] 위 종류에 포함되지 않는 기여

PR 설명
============
prototype_source의  
[tracing_based_selective_build](https://github.com/hyoyoung/22-tutorials-ex/blob/master/prototype_source/tracing_based_selective_build.rst) 번역 

7.22 현재 번역 진행 중이며, commit 업데이트 해서 완성하겠습니다.

2022-07-23 05:19 UTC, YunjinJo reviewed
수정 사항 남겼습니다.
중간에 문체 이슈의 경우 다른 분들의 의견도 들어보고 싶습니다.

2022-07-23 05:19 UTC, YunjinJo commented on prototype_source/tracing_based_selective_build.rst
> +만약 추적기가 모바일 인터프리터가 아닌 다른 환경에서 실행하면, 작동자 리스트가 실제 사용된 작동자 리스트와 다를 수 있고 빠진 작동자들이 오류를 발생 시킬수 있습니다.
작동자 -> 연산자 로 번역하는 것이 더 자연스러울 것 같습니다.

2022-07-23 05:19 UTC, YunjinJo commented on prototype_source/tracing_based_selective_build.rst
> +이 튜토리얼은 모바일 인터프리터 사이즈를 더욱 더 최소화 하기위해, 모바일 인터프리터 빌드를 커스터마이즈하는 새로운 방법을 소개합니다. 이것은 컴파일된 이진 파일에 포함되는 작동자들을 목표 모형에 실제로 필요로하는 작동자 집합 만큼으로 제한합니다. 파이토치의 모바일 배포의 이진 파일 사이즈를 줄이는 기술입니다. 추적 기반 선택적 빌드는 모형을 특정 대표
모형 -> 모델
작동자 -> 연산자

2022-07-23 05:19 UTC, YunjinJo commented on prototype_source/tracing_based_selective_build.rst
> +1. **Tracing-based build libtoㄴrch lite for android**: Build libtorch for android for all 4 android abis (``armeabi-v7a``, ``arm64-v8a``, ``x86``, ``x86_64``) by running
libtoㄴrch 오타 있습니다.

2022-07-23 05:19 UTC, YunjinJo commented on prototype_source/tracing_based_selective_build.rst
> +1. *인풋들과 모델을 준비한다.*
준비 과정도 ~~ 합니다 체로 쓰는게 좋다고 생각하는데 다른 분들의 의견도 들어봐야 할 것 같네요.

2022-07-23 06:05 UTC, bub3690 commented on prototype_source/tracing_based_selective_build.rst
> +1. *인풋들과 모델을 준비한다.*
네 저도 합니다. 체가 맞는 것 같네요

2022-07-23 06:06 UTC, bub3690 commented on prototype_source/tracing_based_selective_build.rst
> +만약 추적기가 모바일 인터프리터가 아닌 다른 환경에서 실행하면, 작동자 리스트가 실제 사용된 작동자 리스트와 다를 수 있고 빠진 작동자들이 오류를 발생 시킬수 있습니다.
감사합니다.
실제, 라이브러리 내부의 연산자를 뜻하는 게 맞나요?

2022-07-23 07:54 UTC, YunjinJo commented on prototype_source/tracing_based_selective_build.rst
> +만약 추적기가 모바일 인터프리터가 아닌 다른 환경에서 실행하면, 작동자 리스트가 실제 사용된 작동자 리스트와 다를 수 있고 빠진 작동자들이 오류를 발생 시킬수 있습니다.
네 operator는 연산자로 번역하는게 일반적이고 여기서 말하는 operator list도 동일한 것으로 보이네요

2022-07-23 16:23 UTC, gorae17 reviewed
고생하셨습니다~ 의견 남겼습니다!

2022-07-23 16:23 UTC, gorae17 commented on prototype_source/tracing_based_selective_build.rst
> +1. *인풋들과 모델을 준비한다.*
윤진님 의견에 동의합니다

2022-07-23 16:23 UTC, gorae17 commented on prototype_source/tracing_based_selective_build.rst
> +(prototype)  추적-기반 선택적 빌드 모바일 Android,iOS 인터프리터
- `추적-기반` 앞에 더블 스페이스로 들어가있습니다. 
- `Android,` 뒤에 스페이스가 없습니다.

2022-07-23 16:23 UTC, gorae17 commented on prototype_source/tracing_based_selective_build.rst
> +추적-기반 선택 빌드는 라이브러리 사이즈를 줄이기 위한 프로토타입 기능입니다. 추적된 결과는 모델 입력과 추적된 환경에 의존 하기때문에,
- `Tracing-based selective build`를 다른 곳에서는 `추적-기반 선택적 빌드`라고 하였는데, 여기서는 `추적-기반 선택 빌드`라고 되어있네요.
- `의존 하기때문에` -> `의존하기 때문에`

2022-07-23 16:23 UTC, gorae17 commented on prototype_source/tracing_based_selective_build.rst
> +1. **추적-기반 libtorch lite Android 빌드**: 모든 4 가지 Android abis를 대상으로 libtorch를 빌드합니다. abis : (``armeabi-v7a``, ``arm64-v8a``, ``x86``, ``x86_64``)
```
**추적-기반 libtorch lite Android 빌드**: 모든 4 가지 Android abis를 대상으로 libtorch를 빌드합니다. abis : (``armeabi-v7a``, ``arm64-v8a``, ``x86``, ``x86_64``)
```
-> 
```
**android를 위한 libtorch lite 추적-기반 빌드**: 모든 4 가지 Android abis(``armeabi-v7a``, ``arm64-v8a``, ``x86``, ``x86_64``)를 대상으로 libtorch를 빌드합니다. 
```
로 바꾸면 어떨까요?
- 추가로, 원문에 android로 되어있는데 번역을 Android로 하신 이유가 있는지 궁금합니다.

2022-07-23 16:23 UTC, gorae17 commented on prototype_source/tracing_based_selective_build.rst
> +빌드가 끝난 후, 라이브러리 경로를 보여줄 것 입니다 :
`것 입니다` -> `것입니다`

2022-07-23 16:23 UTC, gorae17 commented on prototype_source/tracing_based_selective_build.rst
> +만약 ``x86``의 Pixel4 emulator에서 테스트 된다면, cmd 에서 ``BUILD_LITE_INTERPRETER=1 ./scripts/build_pytorch_android.sh x86`` 사용하여, 빌드 시간을 절약하기 위해 abi를 명시 해줍니다.
`Pixel4` -> `Pixel 4`

2022-07-23 16:23 UTC, gorae17 commented on prototype_source/tracing_based_selective_build.rst
> +이 튜토리얼에서는, Android와 iOS App에서 효율적인 Pyotorch 모바일 인터프리터를 커스텀 빌드하는 새로운 방법을 시연했습니다 - 추적-기반 선택적 빌드.
`이 튜토리얼에서는, Android와 iOS App에서 효율적인 Pyotorch 모바일 인터프리터를 커스텀 빌드하는 새로운 방법인 추적-기반 선택적 빌드를 시연했습니다.` 로 하면 어떨까요?

2022-07-23 16:23 UTC, gorae17 commented on prototype_source/tracing_based_selective_build.rst
> +이미지 영역 분할 예제를 수행하며 모델에 들어갈 인풋을 어떻게 묶는지 보여주었고, 묶인 인풋과 모델을 추적함으로써 연산자 리스트를 생성했고,  추적된 결과의 연산자 리스트와 소스로 커스텀 torch 라이브러리를 빌드했습니다.
`추적된 결과` 앞에 더블 스페이스가 들어가있습니다.

2022-07-23 16:23 UTC, gorae17 commented on prototype_source/tracing_based_selective_build.rst
> +다음은  추적-기반 선택적 방법으로 커스텀 모바일 인터프리터를 제작하는 과정들입니다.
`추적-기반` 앞에 더블 스페이스가 들어가있습니다.

2022-07-23 22:11 UTC, YunjinJo approved these changes

2022-07-24 08:48 UTC, bub3690 commented on prototype_source/tracing_based_selective_build.rst
> +1. **추적-기반 libtorch lite Android 빌드**: 모든 4 가지 Android abis를 대상으로 libtorch를 빌드합니다. abis : (``armeabi-v7a``, ``arm64-v8a``, ``x86``, ``x86_64``)
좋은 의견 감사합니다. 훨씬 자연스럽네요.

android는 실수네요.

2022-07-24 08:48 UTC, bub3690 commented on prototype_source/tracing_based_selective_build.rst
> +이 튜토리얼에서는, Android와 iOS App에서 효율적인 Pyotorch 모바일 인터프리터를 커스텀 빌드하는 새로운 방법을 시연했습니다 - 추적-기반 선택적 빌드.
더 자연스럽네요!

2022-07-24 09:07 UTC, hyoyoung requested changes
전반적으로 잘되어있습니다
몇가지 수정 부탁드립니다

2022-07-24 09:07 UTC, hyoyoung commented on prototype_source/tracing_based_selective_build.rst
> +*저자*: Chen Lai <https://github.com/cccclai>, Dhruv Matani <https://github.com/dhruvbird>
저자 아랫줄에 번역에 관련된 정보를 보통 넣어줍니다

2022-07-24 09:07 UTC, hyoyoung commented on prototype_source/tracing_based_selective_build.rst
> +이 튜토리얼은 모바일 인터프리터 사이즈를 더욱 더 최소화 하기위해, 모바일 인터프리터 빌드를 커스터마이즈하는 새로운 방법을 소개합니다. 이것은 컴파일된 이진 파일에 포함되는 연산자들을 목표 모델에 실제로 필요로하는 집합 만큼으로 제한합니다. 파이토치의 모바일 배포의 이진 파일 사이즈를 줄이는 기술입니다. 추적 기반 선택적 빌드는 모델을 특정 대표 입력값들
'이것은' 같은 주어는 필요가 없을듯합니다

2022-07-24 09:07 UTC, hyoyoung commented on prototype_source/tracing_based_selective_build.rst
> +1. *인풋들과 모델을 준비한다.*
인풋들이라고 하니 어색하게 보이는데 적절히 의역이 필요한 듯합니다

2022-07-24 09:07 UTC, hyoyoung commented on prototype_source/tracing_based_selective_build.rst
> +2. **이미지 영역 분할 App 소스에서 빌드된 Pytorch Android 라이브러리를 사용합니다.**: 경로에 `libs` 폴더를 생성, 경로는 root 저장소로 부터 `ImageSegmentation/app/libs`가 됩니다.
생성보다는 조금 더 쉬운 단어인, 만들고 정도가 어떨까요

2022-07-24 09:07 UTC, hyoyoung commented on prototype_source/tracing_based_selective_build.rst
> +``ImageSegmentation/app/build.gradle``에서 `dependencies` 파트를 다음 코드와 같이 수정합니다 :
'파트'보다는 부분이 조금 더 쉬운 단어일듯 합니다

2022-07-24 09:38 UTC, updaun approved these changes
와우 고생하셨습니다! 👍

2022-07-24 09:53 UTC, bub3690 commented on prototype_source/tracing_based_selective_build.rst
> +1. *인풋들과 모델을 준비한다.*
'입력 데이터'는 어떤가요?

2022-07-24 10:14 UTC, hyoyoung commented on prototype_source/tracing_based_selective_build.rst
> +1. *인풋들과 모델을 준비한다.*
'입력 데이터'도 괜찮습니다
아래 문단에서는 bundle을 묶인으로 번역하셨으니
모델과 함께 묶인 입력을 준비합니다 정도도 좋을거 같네요

2022-07-24 10:51 UTC, gorae17 approved these changes

2022-07-28 00:14 UTC, hyoyoung approved these changes
good

2022-07-28 03:06 UTC, merged