docs: translate recipes_source/torchscript_inference.rst
hyoyoung/22-tutorials-ex pull request #7
Opened 2022-07-20 13:37 UTC by terri1102

## 라이선스 동의
 기여하기 문서를 확인하였으며, 본 PR 내용에 BSD 3항 라이선스가 적용됨에 동의합니다.

## 관련 이슈 번호
이슈 번호(#4): https://github.com/hyoyoung/22-tutorials-ex/issues/4

## PR 종류
[] 오탈자를 수정하거나 번역을 개선하는 기여
[x] 번역되지 않은 튜토리얼을 번역하는 기여
[] 공식 튜토리얼 내용을 반영하는 기여
[] 위 종류에 포함되지 않는 기여

## PR 설명
recipes_source에서 torchscript_inference.rst를 번역하였습니다.

2022-07-21 07:29 UTC, hjvision96 commented
자연스럽고 친절하게 번역되었고, 중간에 깔끔하게 단어처럼 자연스럽게 번역된 점도 좋았습니다!
고생하셨습니다~!

2022-07-23 03:58 UTC, sne12345 reviewed
코멘트 달아봤는데, 어떤지 한번 봐주세요!!

2022-07-23 03:58 UTC, sne12345 commented on recipes_source/torchscript_inference.rst
> +TorchScript는 Pytorch 모델을 scalable한 추론을 위해 권장되는 모델 형식입니다.
scalable 을 '확장 가능한'으로 번역하는 건 어떤가요?

2022-07-23 03:58 UTC, sne12345 commented on recipes_source/torchscript_inference.rst
> +이는 모델 연산의 런타임 최적화를 실행하는 **PyTorch JIT Compiler** 에 의해 사용되는 Python의 고성능 subset입니다.
subset은 '하위 집합'으로 표현하면 될 것 같은데, 어떤가요??

2022-07-24 08:16 UTC, hyoyoung requested changes
전반적으로 잘 해주셨습니다
약간의 수정이 필요합니다

2022-07-24 08:16 UTC, hyoyoung commented on recipes_source/torchscript_inference.rst
>  ------------
위에 고쳐진 소문단의 길이에 맞게 -가 늘어나야합니다

2022-07-24 08:16 UTC, hyoyoung commented on recipes_source/torchscript_inference.rst
> +C++ 컴파일러는 사용자의 플랫폼에 따라 달라집니다.
C++ 컴파일러는 사용자의 플랫폼에 따라 달라집니다. 문장은 조금 더 의역해도 좋을 듯합니다
사용자의 플랫폼에 따라 다른 C++ 컴파일러를 사용해야합니다. 정도는 어떨까요

2022-07-24 08:16 UTC, hyoyoung commented on recipes_source/torchscript_inference.rst
> +**TorchScript** 는 C++ 같은 고성능 환경에서 실행할 수 있는 PyTorch 모델(``nn.Module``의 하위 클래스)의 중간 표현(intermediate representation)입니다.
위에 원본 문장 자체의 길이를 그대로 따라할 필요는 없으나
한 문장이 너무 길어지면 적절히 줄내림 하는게 좋을듯합니다

2022-07-24 10:46 UTC, terri1102 commented on recipes_source/torchscript_inference.rst
> +TorchScript는 Pytorch 모델을 scalable한 추론을 위해 권장되는 모델 형식입니다.
오 좋습니다. 수정하겠습니다!

2022-07-24 10:47 UTC, terri1102 commented on recipes_source/torchscript_inference.rst
> +이는 모델 연산의 런타임 최적화를 실행하는 **PyTorch JIT Compiler** 에 의해 사용되는 Python의 고성능 subset입니다.
저도 이렇게 번역하는 것을 고려해보았는데 '하위 집합'이라는 단어가 좀 번역투 같아서 고민이 됩니다.
그래도 subset으로 영어 단어로 쓰는 것보다는 좋아보이네요.
의견 감사드립니다!

2022-07-24 10:48 UTC, terri1102 commented on recipes_source/torchscript_inference.rst
>  ------------
네 수정하겠습니다!

2022-07-24 10:50 UTC, terri1102 commented on recipes_source/torchscript_inference.rst
> +**TorchScript** 는 C++ 같은 고성능 환경에서 실행할 수 있는 PyTorch 모델(``nn.Module``의 하위 클래스)의 중간 표현(intermediate representation)입니다.
네 그쪽이 더 가독성이 좋겠네요.
수정하겠습니다!

2022-07-24 10:53 UTC, terri1102 commented on recipes_source/torchscript_inference.rst
> +C++ 컴파일러는 사용자의 플랫폼에 따라 달라집니다.
앞의 문장과 이어지는 느낌을 주기 위해 'C++ 컴파일러'를 주어로 쓰는 것이 좋을 것 같은데 어떤가요?
-> C++ 컴파일러는 사용자의 플랫폼에 따라 다른 것을 사용해야합니다.

2022-07-24 11:51 UTC, hyoyoung commented on recipes_source/torchscript_inference.rst
> +C++ 컴파일러는 사용자의 플랫폼에 따라 달라집니다.
넵 더 나은 방법인듯합니다 👍

2022-07-24 14:17 UTC, hyoyoung approved these changes
good

2022-07-24 14:17 UTC, hyoyoung commented on recipes_source/torchscript_inference.rst
> +추가 정보를 위해서 `pytorch.org`_의 `TorchScript 튜토리얼 시작하기`_, `TorchScript 모델을 C++에서 불러오는 튜토리얼`_, `TorchScript 문서`_를 참고하세요.
원문처럼 적당한 지점에서 줄내림 부탁드립니다.

2022-11-09 04:40 UTC, closed without merging